FROM quay.io/sampandey001/secktor
RUN git clone https://github.com/Hossam5Arther/ELSA_BOT-V2 /root/elsabot2
WORKDIR /root/Arthut1/
RUN npm install npm@latest
RUN npm install
EXPOSE 8000
CMD ["npm", "start"]
